---
# yamllint disable rule:line-length

stages:
  - init
  - code-analysis
  - code-gating
  - build
  - artifact
  - deploy

variables:
  PROJECT: "mgmt"

include:
  - project: 'nodeai/pipeline-templates'
    ref: main
    file:
      - 'global/rules.yml'
      - 'go/lint.yml'
      # - 'go/unitTest.yml'
      - 'go/build.yml'
      - 'git/actions.yml'
      - 'aws/lambda.yml'
      - 'aws/s3.yml'

########################
### Pre Merge
########################
go_lint_golangci:
  stage: code-analysis
  rules:
    - !reference [.skip_ci, rules]
    - !reference [.pre_merge, rules]

########################
### Merge Request
########################
git_version_gating:
  stage: init
  rules:
    - !reference [.skip_ci, rules]
    - !reference [.merge_request, rules]

# go_unitTest_runTests:
#   stage: code-analysis
#   rules:
#     - !reference [.merge_request, rules]

# go_unitTest_codeCoverage:
#   stage: code-gating
#   rules:
#     - !reference [.merge_request, rules]

# go_unitTest_gating:
#   stage: code-gating
#   variables:
#     ACCEPTABLE_COVERAGE: 80
#   rules:
#     - !reference [.merge_request, rules]

go_build_code:
  stage: build
  rules:
    - !reference [.merge_request, rules]
    - !reference [.post_merge, rules]

########################
### Post Merge
########################
go_build_zip_code:
  stage: build
  needs:
    - go_build_code
  rules:
    - !reference [.post_merge, rules]

aws_push_to_s3:
  stage: artifact
  variables:
    BUCKET_NAME: lambda-source-code-mgmt-dev.nodestack.cloud
  rules:
    - !reference [.post_merge, rules]

lambda_deploy_dev:
  extends: .aws_lambda_deploy
  stage: deploy
  variables:
    ENVIRONMENT: "dev"
    S3_BUCKET: "lambda-source-code-mgmt-dev.nodestack.cloud"
  rules:
    - !reference [.post_merge, rules]

# lambda_deploy_staging:
#   extends: .aws_lambda_deploy
#   stage: deploy
#   variables:
#     ENVIRONMENT: "staging"
#   rules:
#     - !reference [.post_merge, rules]

# lambda_deploy_prod:
#   extends: .aws_lambda_deploy
#   stage: deploy
#   variables:
#     ENVIRONMENT: "prod"
#   rules:
#     - !reference [.post_merge, rules]

git_actions_tag:
  stage: build
  rules:
    - !reference [.post_merge, rules]
